language: node_js

node_js:
    - "0.10"

before_install:
    - sudo apt-get update -qq

before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - make build

script:
    - make ci-test
